### ISSUE TITLE
Java heap allocated memory too low

### ISSUE THREAD

**Issue by RossWickham** [mkoohafkan/dssrip2#16] opened 2023-11-02 19:23 UTC
When performing a `dss_catalog` call on a large DSS file, the JVM may run out of heap space, producing the error: 

java.lang.OutOfMemoryError: Java heap space

The solution is to set the JVM parameter prior to the `library` call to dssrip2, increasing the allocated JVM memory. e.g.:

options(java.parameters = "-Xmx8000m")
library(dssrip2) 

If dssrip2 could increase allocated memory prior to launching the JVM, that would be ideal.

**Comment by mkoohafkan** [comment] 2023-11-03 00:44
Duplicate of #4, #15 

I'm against forcing a specific value for the `java.parameters` option for several reasons, and the options are ignored if the JVM is already initialized (for example, if a user already loaded another package that depends on rJava) so it is not a safe solution in any case. I previously added information to the [documentation](https://github.com/mkoohafkan/dssrip2/commit/5ea5942489a407a7e52e488ce6def80e3a8fc46b) of functions likely to trigger these errors and [a vignette on Java options](https://github.com/mkoohafkan/dssrip2/commit/c7700995829e5930e0f591d0bb3137aa65779af9), but I'll look into whether I can inspect the memory allocated to the JVM and warn the user if it is too low (on package startup or when calling `dss_connect()`).

**Closed** 2023-11-03 22:23 UTC
